spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 25
      minimum-idle: 10
      pool-name: DatebookHikariCP
    type: com.zaxxer.hikari.HikariDataSource
    username: ggbond
    password: 42454434
    url: jdbc:postgresql://192.168.31.117:5432/bot?currentSchema=dev&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
  data:
    redis:
      host: 192.168.31.117
      port: 6379
      password: zhou@42454434
      database: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ouhaochen.bot.xbot.entity
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-generated-keys: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  global-config:
    banner: false
    db-config:
      schema: dev

knife4j:
  enable: true

redis:
  enabled: true