server:
  port: 8086

spring:
  application:
    name: "x-bot"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  config:
    additional-location: file:./config/
  profiles:
    active: "dev2"
  task:
    execution:
      thread-name-prefix: "x-bot-task-"
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        keep-alive: 60

shiro:
  ws:
    server:
      enable: true
      url: "/ws/xbot"
  plugin-list:

x-bot:
  version: "v1.0.0"
  formatted-version: " (v1.0.0)"
  supervisors: 549283548